### ISSUE TITLE
can't run pygal in my environment

### ISSUE THREAD

**Issue by alexwenbj** [trinketapp/pygal.js#6]
My code is like below:
---------------------------
`var myPromise = Sk.misceval.asyncToPromise(function() {
               return Sk.importMainWithBody("<stdin>", false, editor.getValue(), true);
            });

Sk.domOutput = function(html) {
            console.log(html);//-->here get the div tag with no content
            return $('body').append(html).children().last();
            //return $('mycanvas').append(html).children().last();
        };

Sk.externalLibraries = {
  pygal : {
    path : '/path/to/pygal.js/__init__.js',
    dependencies : [
      '/path/to/highcharts.js',
      '/path/to/highcharts-more.js'
    ]
  }
};`
-------------------------------------
Would you please tell me why the function(html) parameter html is an empty &lt;div&gt; tag?(with no content)

**Comment by brianpmarks** [comment]
Hard to tell without seeing your real paths. Here's a complete example that worked for me: https://trinket.io/embed/html/4642c05cb4

Hopefully it'll help you but let me know if you still have questions or problems.

**Comment by alexwenbj** [comment]
Thank you,sir,I will try it and tell you the result.

**Comment by alexwenbj** [comment]
It is OK now,thank you again.
